### PR TITLE
Remove if else code around caseid being present in sdx receipt rrm

### PR DESCRIPTION
**Pull request by insacuri**
## What? and Why?
https://trello.com/c/bJZQZ9Tc/2333-remove-if-else-code-around-caseid-being-present-in-sdx-receipt-rrm

Now that rrm no longer exists, there is a bunch of code that needs to be updated/removed.  We can assume there will always be a case id, otherwise we'll quarantine the receipt.

To test this, in the repos mentioned below, check out the branches with the same name as this branch:
sdx-console: https://github.com/ONSdigital/sdx-console/pull/137
sdx-mock-receipt: https://github.com/ONSdigital/sdx-mock-receipt/pull/12

Put though some submissions and it should go through (EDIT: and receipt) without a problem.

## Checklist
  - [x] CHANGELOG.md updated? (if required)

### CODE REVIEW

**Comment by bitdivision** [comment]
I've done basic testing and haven't had any problems. The code looks fine, but I'm not really familiar enough with this to approve.

**Review by dcdarrell9 — DISMISSED** [review]

**Review by dcdarrell9 — DISMISSED** [review]

**Comment by jonnyshaw89** [comment]
@insacuri can you make the title pretty?

**Comment by insacuri** [comment]
@jonnyshaw89 Prettified it!

**Review by AndrewTorrance — DISMISSED** [review]
I THINK , that RECEIPT_HOST, PATH, _USER, _PASS variables in settings are no longer needed and can be removed. If this is so then it should also come out of readme , yml  etc

**Comment by insacuri** [comment]
@AndrewTorrance Can you look at it again, I removed those unused variables.

**Review by dcdarrell9 — APPROVED** [review]

**Review by bitdivision — APPROVED** [review]

**Comment by bitdivision** [comment]
@insacuri Probably need to dismiss Andrew's review.

**Pull request merged**
